
CREATE TABLE Users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    firstName VARCHAR(255) NOT NULL,
    lastName VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(255) UNIQUE,
    address VARCHAR(255),
    birth VARCHAR(255),
    lastLogin TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    createAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);